@{
    # Main Menu
    VRMonitorNotRunning = "The VR Monitor process is not running. Restarting it..."
    MainMenuTitle = "=== Main Menu ==="
    StreamHeadset = " [ID]. Stream headset screen "
    EnableWifiADB = " +. Enable Wifi ADB on a connected headset "
    AddModifyHeadset = " A. Add/modify a headset "
    ScrcpyTracking = " S. Scrcpy process tracking management "
    RecordingManagement = " R. Recording management "
    FilesFolders = " F. Files and folders management "
    Quit = " 0. Quit "
    AnyOtherKey = " Any other key : Refresh"
    KnownHeadsets = "=== KNOWN HEADSETS ==="
    EnterChoice = "Enter your choice"
    TryingConnection = "Trying connection to {0} - {1}"
    PingKO = "PING {0} KO -> Return to previous menu in 5s."
    AddHeadsetTitle = "== ADD A HEADSET =="
    ScrcpyTrackingTitle = "== SCRCPY PROCESS TRACKING MANAGEMENT =="
    RecordingTitle = "== HEADSET RECORDING MANAGEMENT =="
    FilesFoldersTitle = "== FILES AND FOLDERS MANAGEMENT =="
    InternetOK = "Network internet connection operational - Ping google.com : {0} ms"
    InternetProblem = " Internet connection problem "
    WifiADBActivation = "== WIFI ADB ACTIVATION FROM USB =="
    Goodbye = "Goodbye !"
    Refresh = "Refresh"
    # SubMenu Stream
    SelectHeadsetToStream = "=== [1] SELECT HEADSET TO STREAM ==="
    AddHeadsetFirst = " Add a headset first ! "
    YourChoiceCancel = " Your choice (0 to cancel) >>"
    ReturnPrevious = "Return to previous menu."
    InvalidID = "Invalid ID '{0}' or unrecognized option. Please enter a valid ID, or '0' to cancel."
    # SubMenu Add
    AddOrModifyHeadset = "=== [2] ADD OR MODIFY A HEADSET ==="
    ScanNetworkAdd = "`t 1. Network scan to add a headset"
    AddManually = "`t 2. Add a headset manually to the list"
    ModifyManually = "`t 3. Modify a headset manually in the list"
    RemoveFromList = "`t 4. Remove a headset from the list"
    ReturnPreviousMenu = "`t 0. Return to previous menu"
    YourChoice = " Your choice >>"
    NetworkScanLaunch = "Launching network scan for headset addition."
    ManualAdd = "Manual addition of a headset."
    ManualModify = "Manual modification of a headset."
    RemoveHeadset = "== REMOVE A HEADSET =="
    InvalidOption = "Invalid option. Please enter 1, 2, 3 or 0."
    # SubMenu Edit
    ModifyHeadsetManually = "=== [3] MODIFY A HEADSET MANUALLY ==="
    NoHeadsetToModify = "No headset to modify."
    EnterIDToModify = "Enter the ID of the headset to modify (or 0 to return to menu)"
    ReturnFromEdit = "Return to previous menu from editing."
    InvalidIDRetry = "Invalid ID. Please try again."
    ModifiableFields = "Modifiable fields :"
    FieldName = "1. Name"
    FieldIPAddress = "2. IPAddress"
    FieldScrcpyAutoRestart = "3. scrcpy_AutoRestart"
    FieldRecording = "4. Recording"
    EnterFieldNumber = "Enter the number of the field to modify (1-4)"
    InvalidFieldNumber = "Invalid field number. Please try again."
    CurrentValue = "Current value of '{0}' : {1}"
    EnterNewValueBool = "Enter the new value for '{0}' (True/False)"
    InvalidBoolValue = "Invalid value. Please enter True or False."
    EnterNewValue = "New value for the field '{0}'"
    # SubMenu Remove
    NoHeadsetFound = "No headset found in the file. No deletion possible."
    NoHeadsetToDelete = "There is no headset to delete."
    RemoveHeadsetTitle = "=== [3] REMOVE A HEADSET ==="
    EnterIDToDelete = "`t [1-{0}] : Enter the ID of the headset to delete "
    DeleteAll = "`t ALL : Delete ALL headsets"
    ReturnPreviousOption = "`t 0   : Return to previous menu"
    ConfirmDeleteAll = "Are you sure you want to delete all headsets ? (y/n)"
    AllDeleted = "All headsets have been deleted from the file."
    AllDeletedMsg = "All headsets have been deleted"
    DeletionCancelled = "Deletion cancelled."
    InvalidIDOrOption = "Invalid ID or unrecognized option. Please enter a valid ID, 'ALL' or '0'."
    # SubMenu Manage
    ManageHeadset = "=== [4] HEADSET MANAGEMENT ==="
    InstallOculusApp = "`t 1. Install Oculus Wifi ADB app on a headset (USB + developer mode required)"
    EnableWifiADBOnly = "`t 2. Enable Wifi ADB on a headset only (USB + developer mode required)"
    InstallApp = "`t 3. Install an application (Not available)"
    LaunchApp = "`t 4. Launch an application in the headset(Not available)"
    KillApp = "`t 5. Kill an application in the headset (Not available)"
    UninstallApp = "`t 6. Uninstall an application in the headset (Not available)"
    InstallOculusTitle = "== INSTALL OCULUS WIFI ADB APP (USB CONNECTION REQUIRED) =="
    StartWifiADB = "== START WIFI ADB (USB CONNECTION REQUIRED) =="
    AppManager = "== APPLICATION MANAGER =="
    NotDeveloped = "This feature is not yet developed"
    UnrecognizedOption = "Unrecognized option. Please enter a valid ID, or '0'."
    ReturnMainMenu = "Return to main menu"
    # SubMenu ScrcpyTracking
    SwitchScrcpyTracking = "=== [5] SWITCH SCRCPY WINDOWS TRACKING ==="
    EnterNumberToModify = "Enter the number of the headset to modify"
    NoHeadsetInFile = "No headset found in the known headsets file."
    IDNameAutoRestart = "[ID] `t NAME `t`t AutoRestart"
    Separator = "------------------------------------------"
    Return = "0. Return"
    Choice = "Choice"
    DeactivateAutoTracking = "Deactivation of automatic scrcpy tracking for headset ID {0} ({1})."
    ActivateAutoTracking = "Activation of automatic scrcpy tracking for headset ID {0} ({1})."
    ReturnPreviousDots = "Return to previous menu..."
    # SubMenu Recording
    SwitchRecording = "=== [6] SWITCH HEADSET RECORDING ==="
    IDNameRecording = "[ID] `t NAME `t`t Recording"
    DeactivateRecording = "Deactivation of recording for headset ID {0} ({1})."
    ActivateRecording = "Activation of recording for headset ID {0} ({1})."
    # SubMenu FilesAndFolders
    FilesAndFoldersManagement = "=== FILES AND FOLDERS MANAGEMENT ==="
    OpenRecordingsFolder = "`t 1. Open recordings folder"
    OpenLogsFolder = "`t 2. Open logs folder"
    OpenAppFolder = "`t 3. Open application folder"
    EditConfigFile = "`t 4. Edit configuration file"
    EditKnownHeadsetsConfig = "`t 5. Edit known headsets config file"
    OpenRecordings = "Opening recordings folder."
    OpenLogs = "Opening logs folder."
    OpenApp = "Opening application folder."
    OpenConfig = "Opening configuration file."
    OpenKnownHeadsets = "Opening known headsets configuration file."
    InvalidOptionFiles = "Invalid option. Please enter 1, 2, 3, 4, 5 or 0."
    # Open-File
    FileNotExist = "The file '{0}' does not exist."
}