@{
    # Main Menu
    VRMonitorNotRunning = "Le processus VR Monitor n'est pas en cours d'execution. Relance..."
    MainMenuTitle = "=== Menu Principal ==="
    StreamHeadset = " [ID]. Streamer l'ecran d'un casque VR "
    EnableWifiADB = " +. Activer Wifi ADB sur un casque connecte en USB "
    AddModifyHeadset = " A. Ajouter/modifier un casque "
    ScrcpyTracking = " S. Gestion du tracking des process scrcpy "
    RecordingManagement = " R. Gestion du Recording "
    FilesFolders = " F. Gestion des fichiers et dossiers "
    Quit = " 0. Quitter "
    AnyOtherKey = " Any other key : Refresh"
    KnownHeadsets = "=== CASQUES CONNUS ==="
    EnterChoice = "Entrez votre choix"
    TryingConnection = "Essai de connexion a {0} - {1}"
    PingKO = "PING {0} KO -> Retour au menu precedent dans 5s."
    AddHeadsetTitle = "== AJOUT D'UN CASQUE =="
    ScrcpyTrackingTitle = "== GESTION DU TRACKING DES PROCESS SCRCPY =="
    RecordingTitle = "== GESTION DU RECORDING DES CASQUES =="
    FilesFoldersTitle = "== GESTION DES FICHIERS ET DOSSIERS =="
    InternetOK = "Connexion reseau internet operationnelle - Ping google.com : {0} ms"
    InternetProblem = " Probleme de connexion a internet "
    WifiADBActivation = "== ACTIVATION WIFI ADB DEPUIS L'USB =="
    Goodbye = "Au revoir !"
    Refresh = "Refresh"
    # SubMenu Stream
    SelectHeadsetToStream = "=== [1] SELECTIONNER LE CASQUE A STREAMER ==="
    AddHeadsetFirst = " Ajoutez d'abord un casque ! "
    YourChoiceCancel = " Votre choix (0 pour annuler) >>"
    ReturnPrevious = "Retour au menu precedent."
    InvalidID = "ID '{0}' invalide ou option non reconnue. Veuillez entrer un ID valide, ou '0' pour annuler."
    # SubMenu Add
    AddOrModifyHeadset = "=== [2] AJOUT OU MODIFICATION D'UN CASQUE ==="
    ScanNetworkAdd = "`t 1. Scan du reseau pour ajouter un casque"
    AddManually = "`t 2. Ajouter un casque manuellement a la liste"
    ModifyManually = "`t 3. Modifier un casque manuellement a la liste"
    RemoveFromList = "`t 4. Suppression d'un casque de la liste"
    ReturnPreviousMenu = "`t 0. Revenir au menu precedent"
    YourChoice = " Votre choix >>"
    NetworkScanLaunch = "Lancement du scan reseau pour ajout de casque."
    ManualAdd = "Ajout manuel d’un casque."
    ManualModify = "Modification manuelle d’un casque."
    RemoveHeadset = "== SUPPRESSION D'UN CASQUE =="
    InvalidOption = "Option invalide. Veuillez entrer 1, 2, 3 ou 0."
    # SubMenu Edit
    ModifyHeadsetManually = "=== [3] MODIFIER UN CASQUE MANUELLEMENT ==="
    NoHeadsetToModify = "Aucun casque a modifier."
    EnterIDToModify = "Entrez l'ID du casque a modifier (ou 0 pour revenir au menu)"
    ReturnFromEdit = "Retour au menu precedent depuis l'edition."
    InvalidIDRetry = "ID invalide. Veuillez recommencer."
    ModifiableFields = "Champs modifiables :"
    FieldName = "1. Name"
    FieldIPAddress = "2. IPAddress"
    FieldScrcpyAutoRestart = "3. scrcpy_AutoRestart"
    FieldRecording = "4. Recording"
    EnterFieldNumber = "Entrez le numero du champ a modifier (1-4)"
    InvalidFieldNumber = "Numero de champ invalide. Veuillez recommencer."
    CurrentValue = "Valeur actuelle de '{0}' : {1}"
    EnterNewValueBool = "Entrez la nouvelle valeur pour '{0}' (True/False)"
    InvalidBoolValue = "Valeur invalide. Veuillez entrer True ou False."
    EnterNewValue = "Nouvelle valeur pour le champ '{0}'"
    # SubMenu Remove
    NoHeadsetFound = "Aucun casque trouve dans le fichier. Aucune suppression possible."
    NoHeadsetToDelete = "Il n'y a aucun casque a supprimer."
    RemoveHeadsetTitle = "=== [3] SUPPRESSION D'UN CASQUE ==="
    EnterIDToDelete = "`t [1-{0}] : Saisir l'ID du casque a supprimer "
    DeleteAll = "`t ALL : Supprimer TOUS les casques"
    ReturnPreviousOption = "`t 0   : Revenir au menu precedent"
    ConfirmDeleteAll = "Êtes-vous sûr de vouloir supprimer tous les casques ? (y/n)"
    AllDeleted = "Tous les casques ont ete supprimes du fichier."
    AllDeletedMsg = "Tous les casques ont ete supprimes"
    DeletionCancelled = "Suppression annulee."
    InvalidIDOrOption = "ID invalide ou option non reconnue. Veuillez entrer un ID valide, 'ALL' ou '0'."
    # SubMenu Manage
    ManageHeadset = "=== [4] GESTION D'UN CASQUE ==="
    InstallOculusApp = "`t 1. Installer l'application Oculus Wifi ADB sur un casque (USB + mode developpeur obligatoire)"
    EnableWifiADBOnly = "`t 2. Activer le Wifi ADB sur un casque uniquement (USB + mode developpeur obligatoire)"
    InstallApp = "`t 3. Installation d'une application (Not available)"
    LaunchApp = "`t 4. Lancement d'une application dans le casque(Not available)"
    KillApp = "`t 5. Kill d'une application dans le casque (Not available)"
    UninstallApp = "`t 6. Desinstallation d'une application dans le casque (Not available)"
    InstallOculusTitle = "== INSTALLATION DE L'APPLICATION OCULUS WIFI ADB (USB CONNECTION REQUISE) =="
    StartWifiADB = "== DEMARRAGE DU WIFI ADB (USB CONNECTION REQUISE) =="
    AppManager = "== GESTIONNAIRE D'APPLICATION =="
    NotDeveloped = "Cette fonctionnalite n'est pas encore developpee"
    UnrecognizedOption = "0ption non reconnue. Veuillez entrer un ID valide, ou '0'."
    ReturnMainMenu = "Retour au menu principale"
    # SubMenu ScrcpyTracking
    SwitchScrcpyTracking = "=== [5] SWITCH DU SUIVI DES FENÊTRES SCRCPY ==="
    EnterNumberToModify = "Saisir le numero du casque a modifier"
    NoHeadsetInFile = "Aucun casque trouve dans le fichier de casques connus."
    IDNameAutoRestart = "[ID] `t NAME `t`t AutoRestart"
    Separator = "------------------------------------------"
    Return = "0. Retour"
    Choice = "Choix"
    DeactivateAutoTracking = "Desactivation du suivi automatique des scrcpy pour le casque ID {0} ({1})."
    ActivateAutoTracking = "Activation du suivi automatique des scrcpy pour le casque ID {0} ({1})."
    ReturnPreviousDots = "Retour au menu precedent..."
    # SubMenu Recording
    SwitchRecording = "=== [6] SWITCH DU RECORDING DES CASQUES ==="
    IDNameRecording = "[ID] `t NAME `t`t Recording"
    DeactivateRecording = "Desactivation du recording pour le casque ID {0} ({1})."
    ActivateRecording = "Activation du recording pour le casque ID {0} ({1})."
    # SubMenu FilesAndFolders
    FilesAndFoldersManagement = "=== GESTION DES FICHIERS ET DOSSIERS ==="
    OpenRecordingsFolder = "`t 1. Ouvrir le dossier des enregistrements"
    OpenLogsFolder = "`t 2. Ouvrir le dossier des logs"
    OpenAppFolder = "`t 3. Ouvrir le dossier de l'application"
    EditConfigFile = "`t 4. Editer le fichier de configuration"
    EditKnownHeadsetsConfig = "`t 5. Editer le fichier de config des casques connus"
    OpenRecordings = "Ouverture du dossier des enregistrements."
    OpenLogs = "Ouverture du dossier des logs."
    OpenApp = "Ouverture du dossier de l'application."
    OpenConfig = "Ouverture du fichier de configuration."
    OpenKnownHeadsets = "Ouverture du fichier de configuration des casques connus."
    InvalidOptionFiles = "Option invalide. Veuillez entrer 1, 2, 3, 4, 5 ou 0."
    # Open-File
    FileNotExist = "Le fichier '{0}' n'existe pas."
}