@echo off
REM ===========================================================
REM  VR HEADSET MANAGER - Kiosk screen setup (ADVANCED)
REM
REM  Generated by VR HEADSET MANAGER on 2026-08-31 01:56:31
REM  Server address baked in below: http://192.168.1.37:8080
REM
REM  Double-click to run. It asks for administrator rights, then
REM  launches the kiosk browser and the reporting agent.
REM
REM  To point it at a different server, pass the IP or URL:
REM      Start-Kiosk-ADVANCED.cmd 192.168.1.50
REM      Start-Kiosk-ADVANCED.cmd http://192.168.1.50:8080
REM ===========================================================
setlocal EnableExtensions

set "SERVER_URL=http://192.168.1.37:8080"
if not "%~1"=="" set "SERVER_URL=%~1"

if "%SERVER_URL%"=="" goto :nourl

REM Accept a bare IP as well as a full URL.
echo.%SERVER_URL% | findstr /B /I /C:"http" >nul
if errorlevel 1 set "SERVER_URL=http://%SERVER_URL%:8080"

REM Re-launch this file elevated if it is not already.
net session >nul 2>&1
if errorlevel 1 (
    echo Requesting administrator rights...
    powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -ArgumentList '%SERVER_URL%' -Verb RunAs"
    exit /b
)

echo Starting the kiosk agent against %SERVER_URL% ...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0Start-KioskAgent.ps1" -ServerUrl "%SERVER_URL%"
exit /b

:nourl
echo.
echo No server address is configured in this file.
echo Re-download the package from VR HEADSET MANAGER, or pass the address:
echo     Start-Kiosk-ADVANCED.cmd 192.168.1.50
echo.
pause
