@echo off
REM ===========================================================
REM  VR HEADSET MANAGER - Kiosk screen setup (BASIC)
REM
REM  Generated by VR HEADSET MANAGER on 2026-08-31 01:56:31
REM
REM  Runs the original launcher: opens the firewall and starts the
REM  browser in kiosk mode, nothing else. No reporting, no remote
REM  power control. Use this if the advanced one gives you trouble.
REM ===========================================================
setlocal EnableExtensions

net session >nul 2>&1
if errorlevel 1 (
    echo Requesting administrator rights...
    powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
    exit /b
)

echo Starting the kiosk browser (basic mode) ...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0Start-KioskChrome.ps1"
