#Requires -Version 5.1
<#
.SYNOPSIS
    Prepares the VR_HEADSET_MANAGER project for a clean release by removing all
    runtime-generated files, caches, logs, and temporary data.

.DESCRIPTION
    Deletes files that are safely regenerated by the application on next run:
      - All log files
      - Generated HTML overlays and monitor pages
      - App icon cache
      - Timer files (website\timer\*.txt, *.run) and data\timer.csv
      - Data caches (installed apps, favorite apps, app names, live status CSV)
      - PID file and mediamtx generated config
      - Scratch test files under docs\
      - Config backup copies and data backup CSVs
      - config\config.json (recreated from templates\config\config.json on first run)

    Does NOT delete by default:
      - data\known_headsets.csv (headset registry)
      - website\assets\ (static source files)
      - website\template\ (pshtml source templates)
      - All source modules, scripts, sources, templates

.PARAMETER WhatIf
    Show what would be deleted without actually deleting anything.

.PARAMETER FullReset
    Also removes data\known_headsets.csv (full factory reset).

.EXAMPLE
    .\Prepare-Release.ps1 -WhatIf
    .\Prepare-Release.ps1
    .\Prepare-Release.ps1 -FullReset
#>
param(
    [switch]$WhatIf,
    [switch]$FullReset
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Resolve project root (one level up from scripts\)
$projectRoot = Split-Path -LiteralPath $PSScriptRoot -Parent

function Remove-ItemSafe {
    param([string]$Path, [string]$Label)
    if (Test-Path -LiteralPath $Path) {
        if ($WhatIf) {
            Write-Host "  [WhatIf] Would delete: $Label" -ForegroundColor Cyan
        } else {
            Remove-Item -LiteralPath $Path -Recurse -Force
            Write-Host "  Deleted: $Label" -ForegroundColor Yellow
        }
        return $true
    }
    return $false
}

function Remove-GlobSafe {
    param([string]$Directory, [string]$Pattern, [string]$Label)
    if (-not (Test-Path -LiteralPath $Directory)) { return }
    $items = Get-ChildItem -LiteralPath $Directory -Filter $Pattern -ErrorAction SilentlyContinue
    foreach ($item in $items) {
        if ($WhatIf) {
            Write-Host "  [WhatIf] Would delete: $Label\$($item.Name)" -ForegroundColor Cyan
        } else {
            Remove-Item -LiteralPath $item.FullName -Force
            Write-Host "  Deleted: $Label\$($item.Name)" -ForegroundColor Yellow
        }
    }
}

function Remove-FolderContents {
    param([string]$Directory, [string]$Label)
    if (-not (Test-Path -LiteralPath $Directory)) { return }
    $items = Get-ChildItem -LiteralPath $Directory -Recurse -ErrorAction SilentlyContinue
    if ($items.Count -eq 0) { return }
    if ($WhatIf) {
        Write-Host "  [WhatIf] Would delete contents of: $Label ($($items.Count) item(s))" -ForegroundColor Cyan
    } else {
        Get-ChildItem -LiteralPath $Directory | ForEach-Object {
            Remove-Item -LiteralPath $_.FullName -Recurse -Force
        }
        Write-Host "  Deleted contents of: $Label ($($items.Count) item(s))" -ForegroundColor Yellow
    }
}

$mode = if ($WhatIf) { " [WhatIf - no changes will be made]" } else { "" }
Write-Host ""
Write-Host "=== VR HEADSET MANAGER - Prepare Release$mode ===" -ForegroundColor White
if ($FullReset) {
    Write-Host "    FullReset: known_headsets.csv will also be removed." -ForegroundColor Magenta
}
Write-Host ""

# --- LOGS ---
Write-Host "[ Logs ]" -ForegroundColor Gray
$logsDir = Join-Path $projectRoot "logs"
Remove-FolderContents -Directory $logsDir -Label "logs\"

# --- GENERATED HTML (website root only, not assets\ or template\) ---
Write-Host "[ Generated HTML ]" -ForegroundColor Gray
$websiteDir = Join-Path $projectRoot "website"
Remove-GlobSafe -Directory $websiteDir -Pattern "*[monitoring].html" -Label "website\"
Remove-GlobSafe -Directory $websiteDir -Pattern "*[video].html"      -Label "website\"
Remove-ItemSafe -Path (Join-Path $websiteDir "monitor.html")       -Label "website\monitor.html"
Remove-ItemSafe -Path (Join-Path $websiteDir "video_monitor.html") -Label "website\video_monitor.html"

# --- TIMER FILES ---
Write-Host "[ Timer files ]" -ForegroundColor Gray
$timerDir = Join-Path $websiteDir "timer"
Remove-FolderContents -Directory $timerDir -Label "website\timer\"

# --- APP ICON CACHE ---
Write-Host "[ App icon cache ]" -ForegroundColor Gray
$iconCacheDir = Join-Path $websiteDir "assets\app_icons"
Remove-FolderContents -Directory $iconCacheDir -Label "website\assets\app_icons\"

# --- DATA CACHES ---
Write-Host "[ Data caches ]" -ForegroundColor Gray
$dataDir = Join-Path $projectRoot "data"
Remove-GlobSafe -Directory $dataDir -Pattern "*_installed_apps.csv" -Label "data\"
Remove-GlobSafe -Directory $dataDir -Pattern "*_favorite_apps.csv"  -Label "data\"
Remove-ItemSafe -Path (Join-Path $dataDir "app_names.csv")          -Label "data\app_names.csv"
Remove-ItemSafe -Path (Join-Path $dataDir "known_headsets_infos.csv") -Label "data\known_headsets_infos.csv"
Remove-ItemSafe -Path (Join-Path $dataDir "timer.csv")               -Label "data\timer.csv"
Remove-ItemSafe -Path (Join-Path $dataDir "webserver.pid")          -Label "data\webserver.pid"

# Data backup CSVs (versioned copies created by the user)
Remove-GlobSafe -Directory $dataDir -Pattern "known_headsets_v*.csv"      -Label "data\ [backup]"
Remove-GlobSafe -Directory $dataDir -Pattern "known_headsets_backup*.csv" -Label "data\ [backup]"
Remove-GlobSafe -Directory $dataDir -Pattern "known_headsets_SCRCPY.csv"  -Label "data\"

# --- CONFIG ---
Write-Host "[ Config ]" -ForegroundColor Gray
$configDir = Join-Path $projectRoot "config"
Remove-ItemSafe -Path (Join-Path $configDir "mediamtx_headsets.yml") -Label "config\mediamtx_headsets.yml"
Remove-ItemSafe -Path (Join-Path $configDir "config.json")           -Label "config\config.json"
# Config backup copies (e.g. "config - Copie.json")
Remove-GlobSafe -Directory $configDir -Pattern "* - Copie*.json" -Label "config\ [backup]"
Remove-GlobSafe -Directory $configDir -Pattern "*_backup*.json"  -Label "config\ [backup]"

# --- DOCS TEST FILES ---
Write-Host "[ Docs test files ]" -ForegroundColor Gray
$docsDir = Join-Path $projectRoot "docs"
Remove-ItemSafe -Path (Join-Path $docsDir "test.ps1")             -Label "docs\test.ps1"
Remove-ItemSafe -Path (Join-Path $docsDir "test_invoke_usb.ps1")  -Label "docs\test_invoke_usb.ps1"
Remove-ItemSafe -Path (Join-Path $docsDir "TODO_AI.txt")          -Label "docs\TODO_AI.txt"
$docsFrDir = Join-Path $docsDir "fr-FR"
Remove-ItemSafe -Path (Join-Path $docsFrDir "test.psd1")          -Label "docs\fr-FR\test.psd1"

# --- FULL RESET (optional) ---
if ($FullReset) {
    Write-Host "[ Full Reset ]" -ForegroundColor Magenta
    Remove-ItemSafe -Path (Join-Path $dataDir "known_headsets.csv") -Label "data\known_headsets.csv"
}

Write-Host ""
if ($WhatIf) {
    Write-Host "=== WhatIf complete. No files were deleted. Re-run without -WhatIf to apply. ===" -ForegroundColor Cyan
} else {
    Write-Host "=== Release preparation complete. ===" -ForegroundColor Green
    Write-Host "    config\config.json will be recreated from templates\config\config.json on first run." -ForegroundColor DarkGray
}
Write-Host ""
